# Generated by Django 5.1 on 2024-09-20 08:07

import snippets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=snippets.models.upload_to),
        ),
        migrations.AddField(
            model_name='snippet',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=snippets.models.upload_to),
        ),
    ]
