# Generated by Django 5.1 on 2024-08-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ma_nv',
            field=models.IntegerField(default=-1, null=True, verbose_name='Mã nhân viên'),
        ),
    ]
